### ISSUE TITLE
Support Functional Stateless Components

### ISSUE THREAD

**Issue by theKashey** [lyft/react-javascript-to-typescript-transform#14]
Currently it just removes prop-types at all, and converts SFC into a simple function.

**Comment by mohsen1** [comment]
Something I love to work on. I would gladly help you implement it if you want to get your hands dirty with TypeScript compiler APIs as well.

**Comment by theKashey** [comment]
As long I really need it - might be I should be a right one to implement it.
Let me dive deeper into the current code to roughly get idea how it works, and then I'll ask you to help.

**Comment by vincentbel** [comment]
I have recently refactor my project to use TypeScript and I've do some work to improve the code base and add more transforms. including:

* Update TypeScript to 2.6 #16
* Stateless Components #23
* Support more PropTypes: #19 
   * `PropTypes.oneOf()` // limited, only support string or number literal array `oneOf(['a', 'b', 'c'])` 
   * `PropTypes.oneOfType()`
   * `PropTypes.arrayOf()`
   * // Maybe more
* Remove `import PropTypes from 'prop-types'`
* React import: `import React, { Component } from 'react'`  => `import * as React from 'react'` // Can be dangerous, need more discussion.

I'd like to polish it up and send some pull requests to review & discuss.
