### ISSUE TITLE
Remove `import PropTypes from 'prop-types'`

### ISSUE THREAD

**Issue by vincentbel** [lyft/react-javascript-to-typescript-transform#26]
[Using PropTypes in any other way than annotating React components with them is no longer supported](https://reactjs.org/warnings/dont-call-proptypes.html#dont-call-proptypes-directly). So I think it's safe to remove the import declaration.

I'll open an PR if you agree this. @mohsen1

**Comment by mohsen1** [comment]
Yes I agree. There is also `import React, {PropTypes} from 'react'` import statement that we need to remove `PropTypes` from named import clause
