### ISSUE TITLE
separate transformers from core

### ISSUE THREAD

**Issue by phra** [lyft/react-javascript-to-typescript-transform#3]
hi,

first of all, nice project!
i need the ability to run my own set of trasformers on a js codebase. ( not react specific )
do you think that in future you will publish the core of this repo as a standalone project and the react trasformers as a dedicated plugin?

thanks.

**Comment by mohsen1** [comment]
Hi,

I thought about that and started [a project around it](https://github.com/mohsen1/tst) but it's more appropriate for TypeScript compiler (`tsc`) itself to expose an API for this. 

Please follow this issue for development of it
https://github.com/Microsoft/TypeScript/issues/16607

If you you think tstc is useful and we shouldn't wait for TypeScript to implement those feature I can spend some time and finish it.

**Comment by phra** [comment]
maybe i can help you with that project!
btw what there is in this repo is enough for what i have to do: basically adding some types in an automated way, so in theory i have just to write my own trasformers and remove the react ones.

**Comment by mohsen1** [comment]
Hopefully tranformers  will become a core TS future
