### ISSUE TITLE
Separate imports and components 

### ISSUE THREAD

**Issue by mohsen1** [lyft/react-javascript-to-typescript-transform#33]
There should be an empty line between import groups and actual component code.

Imports should be grouped by:

- lib imports like React and moment
- Relative other component imports 
- Absolute other component imports 
- CSS and image imports 

There should  be an empty line after type declarations

In a multi-component file, there should be an empty line between components 

There should be an empty line above export statements

**Comment by mohsen1** [comment]
This must be done as a Prettier plugin so it can be used in other tools as well

https://prettier.io/docs/en/plugins.html

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
