### ISSUE TITLE
Code Of Conduct goes no where

### ISSUE THREAD

**Issue by benbayard** [lyft/react-javascript-to-typescript-transform#35]
Hey y'all, just clicking around and the code of conduct 1.4 link goes no where.

**Comment by mohsen1** [comment]
You mean the link here?
https://github.com/lyft/react-javascript-to-typescript-transform/blob/master/CODE_OF_CONDUCT.md

**Comment by benbayard** [comment]
Which links here: http://contributor-covenant.org/version/1/4/code_of_conduct.md

**Comment by benbayard** [comment]
Sorry ,this is in the wrong repo!
