### ISSUE TITLE
Named-function SFCs get mistransformed

### ISSUE THREAD

**Issue by akx** [lyft/react-javascript-to-typescript-transform#38]
I have an SFC written as a named function, so it can be default-exported with the name intact:

```javascript
export default function PopoverConfirmedButton({...}) { ... }
```

This gets transformed into
```typescript
export default const PopoverConfirmedButton: React.SFC<PopoverConfirmedButtonProps> = ({...}) { ... }
```

which is [not a valid ES export statement](https://stackoverflow.com/questions/36261225/why-is-export-default-const-invalid), so the Prettier step chokes and I get `Failed to convert js/components/PopoverConfirmedButton.jsx`.

The correct transformation would probably be

```typescript
const PopoverConfirmedButton: React.SFC<PopoverConfirmedButtonProps> = ({...}) { ... }
export default PopoverConfirmedButton;
```

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
