### ISSUE TITLE
Tslint integration?

### ISSUE THREAD

**Issue by akx** [lyft/react-javascript-to-typescript-transform#43]
It would be nice if Tslint was also integrated somehow, since Prettier is.

Right now my workflow is running the CLI followed by `tslint --fix` (well, integrated into PyCharm, but that's beside the point) on the transformed files, followed by manual adjustments.

**Comment by mohsen1** [comment]
It would be nice to have that too. What kind of things you see tslint is fixing?

**Comment by akx** [comment]
It's converting Props/State `type`s to `interface`s (which is a policy question) (with semicolons instead of commas), adding trailing commas, etc.

I suppose the transform could just look for a `tslint.json` in the project root, and if one exists, run `tslint --fix` on the generated file?

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
