### ISSUE TITLE
create typedefs only?

### ISSUE THREAD

**Issue by velohomme** [lyft/react-javascript-to-typescript-transform#44]
I have a library of React SFC components.   The library is using Proptypes currently. We have both typescript and non-typescript apps which need to use the library.  It would be great if we could generate the typedefs only (don't alter the react components...just create the typedefs).  Is it possible to call the CLI to just ouput typedefs?

**Comment by mohsen1** [comment]
This is something that could be useful for libraries as they are not conttolling their host language. I am open to the idea and would love to see someone implement it. 

The way it should be done is to write a general typescript-to-tsd transformer (maybe there is one already?) and apply it at the end if a CLI flag for generating dts files is provided

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
