### ISSUE TITLE
export types as well

### ISSUE THREAD

**Issue by ethanshar** [lyft/react-javascript-to-typescript-transform#45]
Hey, 
Is it possible to export the generated types as well ? currently only the component is exported.
So in the following example I would like to also export `SomeComponentProps`.

```
import React, { Component } from "react";
import { View, Text } from "react-native";
type SomeComponentProps = {
  label?: string,
  color?: string
};
class SomeComponent extends Component<SomeComponentProps, {}> {
  state = {};
  render() {
    return (
      <View>
        <Text>SomeComponent</Text>
      </View>
    );
  }
}
export default SomeComponent;
```

**Comment by mohsen1** [comment]
Yes. We should export types if component is exported. A PR is welcome!

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
