### ISSUE TITLE
Is there a way to silence the "No parser" error message

### ISSUE THREAD

**Issue by velohomme** [lyft/react-javascript-to-typescript-transform#48]
I currently see this message when I run the CLI: "No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred."  Is this expected?  Is there a way to quiet it?

**Comment by mohsen1** [comment]
This is probably Prettier complaining about the parser option. The newer version of Prettier detect the language but maybe when used programmatically we need to set the parser option.

Please try updating prettier and let us know how that goes

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
