### ISSUE TITLE
Bad code formatting

### ISSUE THREAD

**Issue by brunolemos** [lyft/react-javascript-to-typescript-transform#49]
It's currently reformating the files with a different config than the one my project uses, and messing with it. For example, it's removing new lines from every code but I don't think that's prettier, prettier respects new lines.

Any way to disable formatting?
And also pass the prettier config path for it to use.
Thanks.

**Comment by dschaller** [comment]
Thank you for you contribution to this repository.

Closing this contribution as this repository is being archived.
