### ISSUE TITLE
 Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by ngohungphuc** [lyft/react-javascript-to-typescript-transform#51]
When I run 

> react-js-to-ts my-react-js-file.js

I got this error

![conemu64_2018-12-02_19-59-18](https://user-images.githubusercontent.com/13591213/49340035-cd88de00-f66c-11e8-8c9f-74ef9a76da0e.png)

Below is my code

```
import React from "react";
import PropTypes from "prop-types";

import {validateInput} from "../../Helper/Validation";

import Spinner from "../ACCAnimation/Spinner.jsx";

const ACCButton = props => {
  let isDisabled;
  if (props.validationArr) {
    const errors = validateInput(props.validationArr);
    isDisabled = props.disabled
      ? true
      : Object
        .keys(errors)
        .some(x => errors[x]);
  }

  const className = props.btnBlocked
    ? "btn btn-primary btn-block"
    : "btn btn-primary";

  if (props.loading) {
    return <Spinner/>;
  } else {
    return (
      <button
        className={className}
        type="submit"
        disabled={isDisabled || props.disabled}
        onClick={props.onClick}>
        {props.label}
      </button>
    );
  }
};

ACCButton.propTypes = {
  loading: PropTypes.bool,
  label: PropTypes.string,
  validationArr: PropTypes.array,
  disabled: PropTypes.bool,
  onClick: PropTypes.func,
  btnBlocked: PropTypes.string
};

export default ACCButton;

```

**Comment by kranse** [comment]
The problem is with this line in compiler.ts: 
`const sourceFiles = program.getSourceFiles().filter(sf => sf.fileName === filePath);`
On windows machines, sf.fileName uses "/" as a path separator while filePath uses "\\"

**Comment by ngohungphuc** [comment]
so what do you suggest ?

**Comment by kranse** [comment]
If you must use Windows and just want a super quick and dirty fix - add `filePath = filePath.split('\\').join('/');` to D:\cache\npm\node_modules\react-js-to-ts\dist\compiler.js around line 30

**Comment by ngohungphuc** [comment]
@kranse I add this to the code
![code_1sr6esuchr](https://user-images.githubusercontent.com/13591213/49629139-755e2d00-fa1a-11e8-8ef0-e2965a323610.png)

And I get following warning is that ok ? 
![explorer_behyd51wdu](https://user-images.githubusercontent.com/13591213/49629145-8c048400-fa1a-11e8-9640-dd36eb73aa87.png)

**Comment by kranse** [comment]
It's probably fine - there is an issue open for that warning: https://github.com/lyft/react-javascript-to-typescript-transform/issues/48

**Comment by ngohungphuc** [comment]
Thank you
